[tool.poetry]
name = "brick-haystack-harmonization"
version = "0.1.0"
description = ""
authors = ["Gabe Fierro <gtfierro@mines.edu>"]
license = "bsd-3-clause"

[tool.poetry.dependencies]
python = "^3.7"
pyaml = "^21.10.1"
rdflib = "^6.1.1"
pydot = "^1.4.2"
brickschema = "0.7.1a2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
