name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7.9]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install Dependencies
      run: poetry install --no-interaction --no-root
    - name: Create new Taxonomy Visualization
      run: poetry run python tools/visualize_taxonomy.py unified_taxonomy.yaml
    - name: Add new viz to repo
      run: |
        git config --local user.name 'automated'
        mv unified_taxonomy.png .github/images
        git add .github/images
        git commit -m 'Updated unified taxonomy viz'
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update Brick report
      run: poetry run python tools/check_brick.py Brick.ttl unified_taxonomy.yaml > brick_report.txt
    - name: Add Brick report to repo
      run: |
        git config --local user.name 'automated'
        git add brick_report.txt
        git commit -m 'Updated Brick report'
